export const ActionTypes = {
    SET_WEATHER: "SET_WEATHER",
    SET_TOURS: "SET_TOURS",
    SET_BOOKED_TOURS: "USER_SET_TOUR",
    USER_ADD_TOUR: "USER_ADD_TOUR",
    UPDATE_BOOKED_TOUR: "UPDATE_BOOKED_TOUR",
    DELETE_BOOKED_TOUR: "DELETE_BOOKED_TOUR",
  };
  