export const ActionTypes = {
    SET_WEATHER: "SET_WEATHER",
    SET_TOURS: "SET_TOURS",
    USER_SET_TOURS: "USER_SET_TOUR",
    USER_ADD_TOUR: "USER_ADD_TOUR",
    USER_UPDATE_TOUR: "USER_UPDATE_TOUR",
    USER_DELETE_TOUR: "USER_DELETE_TOUR",
  };
  